FROM hoshizora/manylinux1-clang_i686_intermediate1

LABEL maintainer='amaya <mail@sapphire.in.net>'

WORKDIR /root

RUN set -eux && \
    `# Install clang 5.0.2 (cont.)` \
    cd llvm.build && \
    (make -j2) & sleep 6900 ; ps $! > /dev/null 2>&1 && kill -9 $!

