FROM hoshizora/manylinux1-clang_x86_64:clang3

LABEL maintainer='amaya <mail@sapphire.in.net>'

WORKDIR /root

RUN set -eux && \
    `# Install deps` \
    yum install -y zlib-devel xz gcc && \
    `# Install clang 4.0.1` \
    cd && \
    curl http://releases.llvm.org/4.0.1/llvm-4.0.1.src.tar.xz \
      | xz -dc \
      | tar xp && \
    mv llvm-4.0.1.src llvm && \
    curl http://releases.llvm.org/4.0.1/cfe-4.0.1.src.tar.xz \
      | xz -dc \
      | tar xp && \
    mv cfe-4.0.1.src llvm/tools/clang && \
    curl http://releases.llvm.org/4.0.1/libcxx-4.0.1.src.tar.xz \
      | xz -dc \
      | tar xp && \
    mv libcxx-4.0.1.src llvm/projects/libcxx && \
    curl http://releases.llvm.org/4.0.1/libcxxabi-4.0.1.src.tar.xz \
      | xz -dc \
      | tar xp && \
    mv libcxxabi-4.0.1.src llvm/projects/libcxxabi && \
    curl http://releases.llvm.org/4.0.1/openmp-4.0.1.src.tar.xz \
      | xz -dc \
      | tar xp && \
    mv openmp-4.0.1.src llvm/projects/openmp && \
    mkdir llvm-build && \
    cd llvm-build && \
    cmake -G "Unix Makefiles" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DLLVM_ENABLE_LIBCXX=true \
      -DCLANG_DEFAULT_CXX_STDLIB=libc++ \
      -DPYTHON_EXECUTABLE=/opt/python/cp27-cp27m/bin/python \
      ../llvm

