FROM hoshizora/manylinux1-clang_x86_64:clang3

LABEL maintainer='amaya <mail@sapphire.in.net>'

WORKDIR /root

RUN set -eux && \
    `# Install deps` \
    yum install -y zlib-devel xz gcc && \
    `# Install clang 6.0.1` \
    cd && \
    wget http://releases.llvm.org/6.0.1/llvm-6.0.1.src.tar.xz -O - \
      | xz -dc \
      | tar xp && \
    mv llvm-6.0.1.src llvm && \
    wget http://releases.llvm.org/6.0.1/cfe-6.0.1.src.tar.xz -O - \
      | xz -dc \
      | tar xp && \
    mv cfe-6.0.1.src llvm/tools/clang && \
    wget http://releases.llvm.org/6.0.1/libcxx-6.0.1.src.tar.xz -O - \
      | xz -dc \
      | tar xp && \
    mv libcxx-6.0.1.src llvm/projects/libcxx && \
    wget http://releases.llvm.org/6.0.1/libcxxabi-6.0.1.src.tar.xz -O - \
      | xz -dc \
      | tar xp && \
    mv libcxxabi-6.0.1.src llvm/projects/libcxxabi && \
    wget http://releases.llvm.org/6.0.1/openmp-6.0.1.src.tar.xz -O - \
      | xz -dc \
      | tar xp && \
    mv openmp-6.0.1.src llvm/projects/openmp && \
    mkdir llvm-build && \
    cd llvm-build && \
    cmake -G "Unix Makefiles" \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_LIBCXX=true \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DPYTHON_EXECUTABLE=/opt/python/cp27-cp27m/bin/python \
      ../llvm

