FROM hoshizora/manylinux1-clang_x86_64_intermediate3:clang6

LABEL maintainer='amaya <mail@sapphire.in.net>'

WORKDIR /root

RUN set -eux && \
    `# Build clang 6.0.1 (cont.)` \
    cd llvm-build && \
    (make -j2) & sleep 6000 ; ps $! > /dev/null 2>&1 && kill -9 $! || :

