FROM hoshizora/manylinux1-clang_x86_64_intermediate4:clang3

LABEL maintainer='amaya <mail@sapphire.in.net>'

WORKDIR /root

RUN set -eux && \
    `# Build clang 3.9.1 (cont.)` \
    cd llvm-build && \
    make -j2 && \
    make install && \
    `# Remove garbages` \
    cd && \
    rm -rf * && \
    yum erase -y zlib-devel xz && \
    rm -rf /var/cache/yum/* && \
    yum clean all

